[edge]
edge-ops ansible_host=mw-edge

[app]
app1 ansible_host=mw-app1
app2 ansible_host=mw-app2

[database]
db1 ansible_host=mw-db1
db2 ansible_host=mw-db2

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
